### ISSUE TITLE
Erreur lors du Give d'item random dans un report

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#101]
![image](https://user-images.githubusercontent.com/38099970/87257648-f7d38c00-c49c-11ea-9ac4-2dd587526112.png)

**Comment by Nashoba24** [comment]
Ce dernier commit devrait corriger l'erreur et toutes celles liées aux inventaires manquants. Si ce n'est pas le cas, je réouvrirai l'issue en 2.0.2
