### ISSUE TITLE
Points de combats régénératifs

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#104]
Les points de combat ne sont plus rendu immédiatement après un combat mais se régénèrent progressivement avec le temps pour limiter le nombre de combats faisable par le joueur. Les combats amicaux ne sont pas affectés.

**Comment by Nashoba24** [comment]
Pour les points de combats régénératifs, il faudra retourner la valeur dans la fonction `getCumulativeHealth` dans Entities.js, la fonction `getMaxCumulativeHealth` est utilisée pour les combats amicaux ( voir #74 )

**Comment by BastLast** [comment]
Clarification : 

- [ ] Rendre des points de combat (les coeurs bleus) aux joueurs ( 50 / 15 min ) <- à définir
 Les points sont rendus à tous les joueurs en même temps (chaque 15 min un give global est fait pour les joueurs qui ne sont pas au max de leur points)
- [ ] Modifier le profil pour faire apparaitre le nombre de cœur max
