### ISSUE TITLE
Issues de certains évents à vérifier

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#118]
Events 25 et 42 à vérifier

cf https://discordapp.com/channels/429765017332613120/448055928105861120/734716757096267827
cf https://discordapp.com/channels/429765017332613120/448055928105861120/734362038196895804

**Comment by BastLast** [comment]
éventuellement check si il y a d'autres problèmes sur cet évent.

**Comment by Nashoba24** [comment]
J'ai ajouté une vérification automatique des évents (commit 4a6daf79e44e25c5f87851326fd3eb0ef3c51098 surtout). Dans le commit f0a916fedfe503a1dc09fd6996854db0d731b823 j'ai aussi ajouté une vérification pour les évents qui ont du temps de perdu mais pas l'effet :clock2: , et je les ai corrigé
