### ISSUE TITLE
Progress bar crash guild command

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#120]
Jul 21 22:11:21 Draftbot-1 node[7737]: (node:7737) UnhandledPromiseRejectionWarning: RangeError: Invalid count value
Jul 21 22:11:21 Draftbot-1 node[7737]:     at String.repeat (<anonymous>)
Jul 21 22:11:21 Draftbot-1 node[7737]:     at global.progressBar (/root/DraftBot-A-Discord-Adventure/src/core/Tools.js:279:33)
Jul 21 22:11:21 Draftbot-1 node[7737]:     at GuildCommand (/root/DraftBot-A-Discord-Adventure/src/commands/guild/GuildCommand.js:78:9)
Jul 21 22:11:21 Draftbot-1 node[7737]:     at async Function.launchCommand (/root/DraftBot-A-Discord-Adventure/src/core/Command.js:187:9)
Jul 21 22:11:21 Draftbot-1 node[7737]:     at async handleMessage (/root/DraftBot-A-Discord-Adventure/src/core/Command.js:97:7)
Jul 21 22:11:21 Draftbot-1 node[7737]:     at async Client.onDiscordMessage (/root/DraftBot-A-Discord-Adventure/index.js:112:7)
Jul 21 22:11:21 Draftbot-1 node[7737]: (node:7737) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
Jul 21 22:11:43 Draftbot-1 systemd[1]: Created slice User Slice of root.

cf https://discordapp.com/channels/429765017332613120/448055928105861120/734742723260841995

**Comment by Aerue** [comment]
Fix sur la branche 2.0.3-equilibrages https://github.com/BastLast/DraftBot-A-Discord-Adventure/commit/3db787fee76776a9451ff41d6e632b075776e9c5
