### ISSUE TITLE
improve dm support

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#126]
Rework du support dm : 

- [x] Les messages privés sont envoyés dans un salon en lecture seule.
- [ ] Le bot répond automatiquement aux dm pour renvoyer vers les liens utils
- [x] Changement du statut du bot

**Comment by Mw3y** [comment]
Peut-être qu'une sélection de messages pré-écrits serait utile.

**Comment by BastLast** [comment]
> 
> 
> Peut-être qu'une sélection de messages pré-écrits serait utile.

pas suffisant

**Comment by BastLast** [comment]
Probable abandon du support en dm. issue close

**Comment by Asemerald** [comment]
TwT
