### ISSUE TITLE
Améliorations du top

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#129]

**Comment by Nashoba24** [comment]
On vient de faire des tests, spam le !top rien qu'à 5 permet de faire saturer le cpu et la ram, il faut donc mettre un anti spam

**Comment by BastLast** [comment]
Il faut absolument supprimer l'itération sur la totalité des joueurs et optimiser la requête bdd

**Comment by Nashoba24** [comment]
Le commit 24c2941 permet d'avoir le top et top week en moins de 10ms + temps pour envoyer le message (= ping du bot). Pour le serveur je n'ai pas trouvé de solution pour le moment, j'ai laissé le début de mon travail. Il faut trouver un moyen d'avoir le rang du joueur sans récupérer toute la table.

**Comment by Aerue** [comment]
Voir la branche https://github.com/BastLast/DraftBot-A-Discord-Adventure/tree/2.0.3-fix-top-command qui contient une table d’agrégation qui se met à jour toutes les 15 minutes, ceci va faciliter et accélérer les tops.

**Comment by BastLast** [comment]
> 
> 
> Voir la branche https://github.com/BastLast/DraftBot-A-Discord-Adventure/tree/2.0.3-fix-top-command qui contient une table d’agrégation qui se met à jour toutes les 15 minutes, ceci va faciliter et accélérer les tops.

je doute de l'utilité de la table d'agrégation en dehors du topserv étant donné les modifs de nashoba.
Les tops doivent être le plus instantané possible imo
