### ISSUE TITLE
Problème commande topserv

### ISSUE THREAD

**Issue by quenquentin** [BastLast/DraftBot-A-Discord-Adventure#132]
Il est actuellement impossible d'effectuer la commande topserv sur le serveur Khundar, cependant la commande reste apparemment disponible sur tout les autres serveurs.

**Comment by Nashoba24** [comment]
Je n'ai pas réussi à reproduire l'erreur, je déplace l'issue en 2.0.3 et on verra si elle se reproduit

**Comment by BastLast** [comment]
issue close en l'absence de reproduction du bug, à reopen en cas de nouveaux signalements
