### ISSUE TITLE
Modification item fastforward

### ISSUE THREAD

**Issue by quenquentin** [BastLast/DraftBot-A-Discord-Adventure#134]
Il faudrait modifier la puissance des items fastforward, de passer la valeur d'heure à demi-heure, (Actuellement 1 de power = 1 heure)
Ex: "power": 1 correspondrait à 30 minutes et "power": 2 correspondrait à 1 heure

**Comment by BastLast** [comment]
En effet pour le moment ces items ne supportent que les heures en brut.

**Comment by BastLast** [comment]
L'affichage des minutes n'est pas fait partout.
![image](https://user-images.githubusercontent.com/38099970/90192491-57d29080-ddc3-11ea-89c7-14cfbdde7c1b.png)
