### ISSUE TITLE
l'xp de cette issue n'est pas calculée correctement

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#138]
"end": [
            {
                "translations": {
                    "fr": " | :person_walking: Vous l'ignorez totalement, et reprenez route. Vous finissez par arriver dans une petite bourgade du très joli nom de Tardans. En y entrant, vous tombez sur une sacoche emplie d'un bon tas de pièces et d'un objet, ce qui pourrait s'avérer utile pour la suite de votre aventure !",
                    "en": " | :person_walking: You ignore her entirely and go on your way. You arrive in a delightful little town whose lovely name is Tardans. Wandering the small streets, you come across a small money bag filled with money and an object, which could be useful for the future of your journey."
                },
                "lostTime": 0,
                "health": 0,
                "effect": ":smiley:",
                "experience": 25,
                "money": 500,
                "item": true

**Comment by quenquentin** [comment]
C'est corrigé dans la pr que je viens de faire. Cette issue peut donc être close.
