### ISSUE TITLE
Distribution des stats

### ISSUE THREAD

**Issue by Asemerald** [BastLast/DraftBot-A-Discord-Adventure#151]
La commmande `test lvl` ne fonctionne qu'a moitié, elle augmente juste le level et les :blue_heart: du joueurs, mais pas sa vitesse, attaque de base et pv max

**Comment by BastLast** [comment]
Peut être un bug pr le moment mais a terme, les stats en question ne vont plus être distribuée automatiquement.

**Comment by BastLast** [comment]
apres chaque passage de niveau
ya un menu
qui te permet de choisir entre boost de vitesse / attaque / def
et un item dans le shop qui permet de reset tout ca à zero et tout redistribuer
et qui coute 10 k

**Comment by BastLast** [comment]
ce syteme est remplacé par le système de classe cf #168
