### ISSUE TITLE
Emoji potion shop

### ISSUE THREAD

**Issue by quenquentin** [BastLast/DraftBot-A-Discord-Adventure#193]
Depuis quelques jours maintenant j'ai l'impression (Minimum aujourd'hui et hier)
L'émoji de la potion du jour ne change pas et il affiche celle du vin rouge au lieu de celle de la potion du jour.

**Comment by pavlekowalski** [comment]
Les dernière potion rajouté n'ont pas été bien déclarées, les emoji sont sous forme `:beverage_box:` alors qu'ils devraient être en forme character pour pouvoir être réagis par le bot   
Quand le bot n'arrive pas à trouver l'emoji, il met cette constante à la place : 
https://github.com/BastLast/DraftBot-A-Discord-Adventure/blob/67159d5ad2dbfe1d1b1f3bd5698e5ddab068139b/src/core/Constant.js#L107

Au passage, les emojis n'avaient même pas été déclarés pareil en fr et en en sur la portion 36 et 37. Ex : 
https://github.com/BastLast/DraftBot-A-Discord-Adventure/blob/67159d5ad2dbfe1d1b1f3bd5698e5ddab068139b/ressources/text/potions/36.json#L3-L4

**Comment by quenquentin** [comment]
Pour la potion 36 et 37 merci de l'information je corrige ça ce week-end.
Et effectivement c'est probablement ce qui cause un petit problème à notre ami le bot.
Je corrige ça également ce week-end si ce n'est pas déjà fait avant.
