### ISSUE TITLE
Ajout d'une intégration continue

### ISSUE THREAD

**Issue by YaFou** [BastLast/DraftBot-A-Discord-Adventure#3]
***Type :** Suggestion*

Comme le projet est développé en `Node.js`, cela pourrait être mieux d'ajouter une intégration continue. Cela aura comme avantage de ne pas avoir d'erreur de compilation dans les [pulls-request](https://github.com/BastLast/DraftBot-A-Discord-Adventure/pulls).
J'ai trouvé une plateforme pouvant être utilisée pour cette requête : [Travis CI](https://travis-ci.org/), il supporte le langage `Node.js` (https://docs.travis-ci.com/user/languages/javascript-with-nodejs/).

**Comment by BastLast** [comment]
Désolé mais je ne veux pas m’embêter avec ça.

**Comment by BastLast** [comment]
3 ans plus tard... on le fait quand même mdr
