### ISSUE TITLE
Problème commande fight

### ISSUE THREAD

**Issue by NonozgYtb** [BastLast/DraftBot-A-Discord-Adventure#38]
Quand on fait un fight, et qu'il renvoit ça :

> :x: | @NonozgYtb Il est impossible de se combattre soi-même ! Trouvez un autre adversaire.

Cela bloque toutes les commandes et il faut cliquer sur la croix rouge du message precedant pour que cela se reset et que tout remarche !

**Comment by BastLast** [comment]
Ceci n'est pas un bug. Il est normal que le joueur ne puisse pas utiliser le bot quand il est demandeur d'un combat et il est normale que le joueur ne puisse pas se combattre lui-même

**Comment by NonozgYtb** [comment]
D'accord ! Pouvez vous m'indiquer où ce trouve le script qui envoit le "❌ | @NonozgYtb Il est impossible de se combattre soi-même ! Trouvez un autre adversaire." ?

**Comment by BastLast** [comment]
dans la commande fight :)

**Comment by NonozgYtb** [comment]
Et quel ligne svp ?
