### ISSUE TITLE
FightCommand

### ISSUE THREAD

**Issue by Aerue** [BastLast/DraftBot-A-Discord-Adventure#61]
Mettre à jour la command fight afin d'utiliser le nouveau coeur de la 2.0.0

**Comment by BastLast** [comment]
Penser à finir l'équilibrage commencé avant le début du refactoring. (je peux m'occuper de cette partie)

**Comment by Nashoba24** [comment]
Je vais déjà faire refactor le code actuel et ensuite j'équilibrerai. Le code sera facile à modifier de toute façon

**Comment by BastLast** [comment]
l'équilibrage était déjà commencé en réalité il suffit de finir la nouvelle attaque ultime.

**Comment by BastLast** [comment]
efb67cf343c9eac68beeb4ea0ffebea78bb6feb7

**Comment by Nashoba24** [comment]
Les fights sont finis selon moi, je ne trouve plus de bugs et les améliorations à faire sont pour la 2.0.1
