### ISSUE TITLE
Finir les commandes admin

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#69]
- [x] Refactor setters innutils
- [x] ResetBadge
- [x] Send
- [x] Servers

**Comment by BastLast** [comment]
TODO : 

-Le bot crash si on ne met pas les arguments dans le bon sens sur la commande give badge. 
-La commande changelanguage semble ne pas fonctionner ?

**Comment by GosuPaper** [comment]
ChangeLanguage fix sur la branche TopCommandRefactoring(oui je sais mais flemme d'une branche pour ca)

**Comment by BastLast** [comment]
@senetal  Possible de transférer ton commit sur ce repo et de faire les tests des commandes si ce n'est pas déjà fait ?

**Comment by BastLast** [comment]
Reset badges terminé : 764283071dbe65782c8aabc5d316921d44661ba5
Aussi divers refactoring effectués sur les autres commandes admins
