### ISSUE TITLE
Core refactor

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#70]
- [x] Gestion de la réception des messages privés
- [x] datasource 
- [x] Gérer la mort du joueur
- [x] Gérer le levelup
- [x] Gestion du blocage inter-commande global
- [x] Transformer la classe progressbar en une fonction

**Comment by Aerue** [comment]
Fix datasource requierment on preinstall : 477b224b6c30f7a37b0b704ab6e85c26fd44850e

**Comment by Mw3y** [comment]
Gestion de la réception des messages privés ✅

**Comment by BastLast** [comment]
@Mw3y  N'oublie pas de mettre l'identifiant de l'issue dans le message de commit pour les lier. Sinon c'est compliqué de suivre les modifications

**Comment by Mw3y** [comment]
Ok

**Comment by BastLast** [comment]
Le bug de la table armor qui n'existe pas semble toujours présent. (cf https://cdn.discordapp.com/attachments/699295728299933727/722211365950849105/unknown.png) malgrès 805c0cfa1af10645d335180aaffd1af671baf662

**Comment by Aerue** [comment]
Je fais une issue à part pour ce problème afin de le traiter #73

**Comment by Aerue** [comment]
J'ai ouvert une issue afin de traiter ce bug en particulier.

**Comment by Nashoba24** [comment]
Gestion de la mort du joueur: 748b7f6b93b6ee4250dc73ba7c8e7ba77a938f90
Gestion du levelup: da3b4374ea327769c9dd217819f7b9d960b20c1b
J'ai donc coché les 2 points correpondants
