### ISSUE TITLE
Upgrade help command

### ISSUE THREAD

**Issue by BastLast** [BastLast/DraftBot-A-Discord-Adventure#77]
- [x] Make the help command work with command aliases.
- [x] Add the invite command 
- [x] Prix création de guilde
- [x] Typo respawn

**Comment by Nashoba24** [comment]
Pour ce qui est d'ajouter la command invite (cf premier message), je pense que ça a déjà été fait, à part si t'attends autre chose.

**Comment by BastLast** [comment]
> 
> 
> Pour ce qui est d'ajouter la command invite (cf premier message), je pense que ça a déjà été fait, à part si t'attends autre chose.

Nope pas du tout ca doit être un oubli.

**Comment by BastLast** [comment]
Je réouvre pour une toute petite modif : https://trello.com/c/LSvubP6h/413-pr%C3%A9ciser-que-cr%C3%A9er-une-guilde-coute-5000-dans-le-message-daide-492348904436662274

**Comment by BastLast** [comment]
et j'ajoute ceci également tant qu'à faire : https://trello.com/c/puv98BJ3/385-avoir-%C3%A9t%C3%A9-mis-ko-serait-plus-ad%C3%A9quat-378513552270557185

**Comment by Nashoba24** [comment]
Une autre amélioration possible serait d'améliorer le !help, car le message est un peu long
